version: "3.0"
services:
  app:
    container_name: pytorch-tutorial-app-dev
    image: pytorch-tutorial_app-dev:latest
    volumes:
      - ../:/root/pytorch-tutorial/
      - venv:/root/pytorch-tutorial/.venv/
      - jupyter-config:/root/.jupyter/
      - ~/.ssh/:/root/.ssh/:ro
      - ~/.gitconfig:/root/.gitconfig:ro
      - ${LOG_PATH}:/root/pytorch-tutorial/logs
      - ${DATASET_PATH}:/root/pytorch-tutorial/datasets/
    ports:
      - ${port:-8888}:8888

  tensorboard:
    container_name: tensorboard
    image: tensorboard:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.tensorboard
    ports:
      - 7000:7000
    environment:
      - SHELL=/bin/bash
    volumes:
      - ${LOG_PATH}:/root/logs
    tty: true
    command: tensorboard --port 7000 --logdir /root/logs --bind_all

volumes:
  venv:
    external:
      name: venv-pytorch-tutorial
  jupyter-config:
    external:
      name: jupyter-config